export const SEO_CONFIG = {
  site: {
    name: "Ganesh Shinde Portfolio",
    url: "https://ganeshshinde2003.netlify.app",
    description:
      "AI product engineer building end-to-end LLM systems, health analysis pipelines, B2B workflows, and CI/CD integrations.",
  },
  author: {
    name: "Ganesh Shinde",
    email: "ganeshshinde2003@gmail.com",
    location: "Bengaluru, Karnataka, India",
    bio: "Full-stack AI product engineer with founding startup experience. Specializes in LLM systems, AI automation, and end-to-end product development.",
  },
  social: {
    github: "https://github.com/Ganeshshinde-2003",
    linkedin: "https://www.linkedin.com/in/dev-ganesh-shinde/",
  },
  keywords: {
    primary: [
      "Ganesh Shinde",
      "AI product engineer",
      "full-stack developer",
      "AI engineer",
      "product engineer",
    ],
    technical: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Tailwind CSS",
      "Node.js",
      "Python",
      "Flutter",
      "Dart",
      "Firebase",
      "MongoDB",
      "MySQL",
    ],
    ai_ml: [
      "LLM systems",
      "Gemini API",
      "Vertex AI",
      "prompt engineering",
      "AI automation",
      "AI workflows",
      "structured JSON output",
      "document analysis",
      "RAG workflows",
      "generative AI",
      "machine learning",
    ],
    domain_specific: [
      "health AI",
      "HealthAI",
      "Stratifai",
      "AI marketing strategy",
      "B2B platform",
      "CI/CD integration",
      "security scanning",
      "GitLab integration",
      "SCM integration",
      "AI SaaS",
      "image editor",
      "Cloudinary",
    ],
    location: ["Bengaluru developer", "India developer", "remote engineer"],
    role_specific: [
      "founding engineer",
      "startup engineer",
      "early engineer",
      "frontend engineer",
      "backend engineer",
      "full-stack engineer",
      "YC startup experience",
    ],
  },
  projects: [
    {
      name: "HealthAI",
      keywords: [
        "AI health analysis",
        "health data analysis",
        "medical AI",
        "health reports",
        "biomarker analysis",
        "Gemini",
        "Vertex AI",
      ],
    },
    {
      name: "Stratifai",
      keywords: [
        "AI marketing strategy",
        "marketing automation",
        "AI SaaS",
        "product marketing",
        "AI copywriting",
        "marketing content generation",
      ],
    },
    {
      name: "Black Duck SCM Integration",
      keywords: [
        "CI/CD integration",
        "GitLab integration",
        "GitHub integration",
        "security scanning",
        "pipeline automation",
        "developer tools",
      ],
    },
    {
      name: "Bewell",
      keywords: [
        "healthtech AI",
        "startup AI engineer",
        "health platform",
        "founding engineer",
        "AI systems design",
      ],
    },
  ],
  allKeywords: [
    "Ganesh Shinde",
    "AI product engineer",
    "full-stack developer",
    "LLM systems",
    "AI engineer",
    "React developer",
    "Next.js developer",
    "TypeScript engineer",
    "Gemini API",
    "Vertex AI",
    "prompt engineering",
    "AI automation",
    "health AI",
    "HealthAI",
    "Stratifai",
    "startup engineer",
    "founding engineer",
    "AI SaaS",
    "product engineer",
    "Flutter developer",
    "backend engineer",
    "frontend engineer",
    "full-stack engineer",
    "Bengaluru developer",
    "India developer",
    "YC startup experience",
    "CI/CD integration",
    "GitLab integration",
    "GitHub integration",
    "security scanning",
    "AI workflows",
    "data analysis",
    "B2B platform",
    "developer tools",
    "AI assistant",
    "generative AI",
    "machine learning engineer",
    "Firebase expert",
    "MongoDB developer",
    "MySQL developer",
    "Node.js developer",
    "Python developer",
    "Tailwind CSS",
    "HTML/CSS expert",
    "responsive design",
    "performance optimization",
    "animation developer",
    "GSAP animation",
    "Electron developer",
    "mobile app developer",
    "web development",
    "API design",
    "database design",
    "cloud development",
    "Google Cloud Platform",
    "healthcare technology",
    "medical data analysis",
    "health tracking",
    "biomarker analysis",
    "marketing strategy AI",
    "content generation AI",
    "AI copywriting",
    "email marketing AI",
    "social media marketing AI",
    "messaging app clone",
    "WhatsApp clone",
    "chat application",
    "social platform",
    "community platform",
    "image editor",
    "Cloudinary integration",
    "media management",
    "file upload",
    "image transformation",
    "startup experience",
    "early-stage startup",
    "AI startup",
    "tech startup",
    "founder collaboration",
    "high-ownership role",
    "end-to-end development",
    "product thinking",
    "system design",
    "architecture design",
    "testing and QA",
    "mentoring developers",
    "technical leadership",
  ],
};

export function generateKeywordsString(): string {
  return SEO_CONFIG.allKeywords.join(", ");
}
